# Generated by Django 3.2.16 on 2022-10-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='content',
        ),
        migrations.AddField(
            model_name='profile',
            name='brake_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='frame_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mallet_length',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='play_style',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='usual_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wheel_size',
            field=models.TextField(blank=True),
        ),
    ]
