# Generated by Django 3.2.16 on 2022-10-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='play_times',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
